# Based off https://github.com/Electrostatics/mmcif_pdbx/blob/master/.github/workflows/python-package.yml
# Also credit to https://github.com/commitizen-tools/commitizen/tree/master/.github/workflows

name: Tests
on: [push, pull_request]

jobs:

  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up MacPorts
      uses: GiovanniBussi/macports-ci-action@master
      with:
        ports: gh
    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry
        poetry --version
        poetry install
    - name: Run Tests
      run: |
        bash ./scripts/tests.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.1.1
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
